##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/test

#C_SRCS += $(TOP_DIR)/test/delay.c
#C_SRCS += $(TOP_DIR)/test/led.c
#C_SRCS += $(TOP_DIR)/test/lcd.c

ASM_SRCS += 

INC_DIR += -I $(TOP_DIR)/test
