##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y = misc.o
obj-y += stm32f10x_adc.o
obj-y += stm32f10x_bkp.o
obj-y += stm32f10x_can.o
obj-y += stm32f10x_cec.o
obj-y += stm32f10x_crc.o
obj-y += stm32f10x_dac.o
obj-y += stm32f10x_dbgmcu.o
obj-y += stm32f10x_dma.o
obj-y += stm32f10x_exti.o
obj-y += stm32f10x_flash.o
obj-y += stm32f10x_fsmc.o
obj-y += stm32f10x_gpio.o
obj-y += stm32f10x_i2c.o
obj-y += stm32f10x_iwdg.o
obj-y += stm32f10x_pwr.o
obj-y += stm32f10x_rcc.o
obj-y += stm32f10x_rtc.o
obj-y += stm32f10x_sdio.o
obj-y += stm32f10x_spi.o
obj-y += stm32f10x_tim.o
obj-y += stm32f10x_usart.o
obj-y += stm32f10x_wwdg.o


