##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

FP_FLAGS	= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS	= -mthumb -mcpu=cortex-m4
OOCD_TARGET	:= stm32f4x
OOCDFLAGS := -f arch/$(ARCH)/board/$(BOARD)/openocd.cfg
OOCDCFG := arch/$(ARCH)/board/$(BOARD)/openocd.cfg
LDSCRIPT += arch/$(ARCH)/board/$(BOARD)/wk_kernel.ld.S
DEFINES += -DSTM32F401xx -DUSE_STDPERIPH_DRIVER -D__VFP_FP__