##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/arch/arm/board/zj_v3

C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/arch_dma.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/arch_uart.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/arch_clk.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/arch_irq.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/arch_gpio.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/board_config.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/board_init.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/console.c

ASM_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/startup_stm32f10x_hd.S

INC_DIR += -I $(TOP_DIR)/arch/arm/board/zj_v3/include



