##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

dir-y = drivers
dir-y += usb

obj-y = arch_dma.o
obj-y += arch_uart.o
obj-y += arch_clk.o
obj-y += arch_irq.o
obj-y += arch_gpio.o
obj-y += board_config.o
obj-y += board_init.o
obj-y += arch_console.o
obj-y += arch_usb.o





