##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

FP_FLAGS	= -msoft-float
ARCH_FLAGS	= -mthumb -mcpu=cortex-m3
OOCD_TARGET	:= stm32f1x
OOCDFLAGS := -f $(project-dir)/arch/$(ARCH)/board/$(BOARD)/openocd.cfg
LDSCRIPT += $(project-dir)/arch/$(ARCH)/board/$(BOARD)/wk_kernel.ld
DEFINES += -DSTM32F10X_HD -DUSE_STDPERIPH_DRIVER