##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y = cmd.o
obj-y += cmd_clear.o
obj-y += cmd_ls.o
obj-y += cmd_log.o
obj-y += cmd_task_show.o
obj-y += cmd_reboot.o
obj-y += cmd_led.o

ASM_SRCS +=


