##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/kernel/cmd

C_SRCS += $(TOP_DIR)/kernel/cmd/cmd.c
C_SRCS += $(TOP_DIR)/kernel/cmd/cmd_clear.c
C_SRCS += $(TOP_DIR)/kernel/cmd/cmd_ls.c
C_SRCS += $(TOP_DIR)/kernel/cmd/cmd_log.c
C_SRCS += $(TOP_DIR)/kernel/cmd/cmd_task_show.c

ASM_SRCS +=


