##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

dir-$(CONFIG-CORTEX-M3) = m3
dir-$(CONFIG-CORTEX-M4) = m4



