##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

dir-y = board
dir-y += boot
dir-y += cmsis
dir-y += cpu
dir-y += config

