##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/arch/arm

include $(TOP_DIR)/arch/arm/board/Makefile
include $(TOP_DIR)/arch/arm/boot/Makefile
include $(TOP_DIR)/arch/arm/cmsis/Makefile
include $(TOP_DIR)/arch/arm/cpu/Makefile
include $(TOP_DIR)/arch/arm/config/Makefile

C_SRCS += 

ASM_SRCS += 
ASM_SRCS += 

INC_DIR += -I $(TOP_DIR)/arch/arm/include



