##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/drivers/usb/device/core

C_SRCS += $(TOP_DIR)/drivers/usb/device/core/core.c
C_SRCS += $(TOP_DIR)/drivers/usb/device/core/usbdevice.c

ASM_SRCS += 

INC_DIR +=
