##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/kernel

include $(TOP_DIR)/kernel/irq/Makefile
include $(TOP_DIR)/kernel/printk/Makefile

C_SRCS += $(TOP_DIR)/kernel/task.c
C_SRCS += $(TOP_DIR)/kernel/clk.c
C_SRCS += $(TOP_DIR)/kernel/sch.c
C_SRCS += $(TOP_DIR)/kernel/kernel.c
C_SRCS += $(TOP_DIR)/kernel/pid.c

ASM_SRCS +=


