##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y = task.o
obj-y += clk.o
obj-y += sch.o
obj-y += kernel.o
obj-y += pid.o
obj-y += timer.o
obj-y += mutex.o
obj-y += msg_queue.o
obj-y += delay.o
obj-y += cpu.o
obj-y += sem.o
obj-y += console.o

dir-y = base
dir-y += cmd
dir-y += irq
dir-y += printk


