##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/kernel/printk

C_SRCS += $(TOP_DIR)/kernel/printk/printk.c
C_SRCS += $(TOP_DIR)/kernel/printk/log.c

ASM_SRCS +=


