##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/kernel/irq

C_SRCS += $(TOP_DIR)/kernel/irq/irq.c

ASM_SRCS +=


