##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/app

C_SRCS += $(TOP_DIR)/app/test_app.c

ASM_SRCS +=


