##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/lib

C_SRCS += $(TOP_DIR)/lib/string.c
C_SRCS += $(TOP_DIR)/lib/vsprintf.c
C_SRCS += $(TOP_DIR)/lib/fifo_buf.c

ASM_SRCS +=
