##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y = stm32f4xx_hal_pcd_ex.o
obj-y += stm32f4xx_hal_pcd.o
obj-y += stm32f4xx_ll_usb.o




