##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/mm

C_SRCS += $(TOP_DIR)/mm/mm_core.c
C_SRCS += $(TOP_DIR)/mm/mm_init.c
C_SRCS += $(TOP_DIR)/mm/mm.c

ASM_SRCS +=
