##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/drivers

include $(TOP_DIR)/drivers/usb/Makefile

C_SRCS += 

ASM_SRCS += 

INC_DIR += 
