##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/arch/arm/cmsis

C_SRCS += $(TOP_DIR)/arch/arm/cmsis/core_cm3.c

ASM_SRCS += 

