##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y = com.o
obj-y += com_updata.o
obj-y += com_version.o


