##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/arch/arm/cpu/m3

C_SRCS += $(TOP_DIR)/arch/arm/cpu/m3/cpu_c.c
C_SRCS += $(TOP_DIR)/arch/arm/cpu/m3/asm_irq.c

ASM_SRCS += $(TOP_DIR)/arch/arm/cpu/m3/cpu_s.S

INC_DIR += -I$(TOP_DIR)/debug/arch/arm/cpu/m3



