##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-y += cpu_c.o
obj-y += asm_irq.o

objs-y += cpu_s.o
objs-y += start.o



