##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/kernel/base

C_SRCS += $(TOP_DIR)/kernel/base/bus.c
C_SRCS += $(TOP_DIR)/kernel/base/device.c
C_SRCS += $(TOP_DIR)/kernel/base/driver.c

ASM_SRCS +=


