##############################################
# Copyright (C) 2019 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

TARGET = wk_os

RM := rm -rf

#定义工具链
PREFIX		:= arm-none-eabi-
CC		    := $(PREFIX)gcc
CXX		    := $(PREFIX)g++
LD		    := $(PREFIX)gcc
AR		    := $(PREFIX)ar
AS		    := $(PREFIX)as
OBJCOPY		:= $(PREFIX)objcopy
OBJDUMP		:= $(PREFIX)objdump
SIZE        := $(PREFIX)size
GDB		    := $(PREFIX)gdb

OPTSRC = -O2

TARGET_HEX = $(project-dir)/$(out-dir)/$(TARGET).hex
TARGET_SIZE = $(project-dir)/$(out-dir)/$(TARGET).size
TARGET_BIN = $(project-dir)/$(out-dir)/$(TARGET).bin
TARGET_ELF = $(project-dir)/$(out-dir)/$(TARGET).elf
TARGET_LIST = $(project-dir)/$(out-dir)/$(TARGET).list
TARGET_MAP = $(project-dir)/$(out-dir)/$(TARGET).map

#头文件文件目录
INC_DIR := -I$(project-dir)/include
INC_DIR += -I$(project-dir)/arch/$(ARCH)/include
INC_DIR += -I$(project-dir)/arch/$(ARCH)/board/include
INC_DIR += -I$(project-dir)/arch/$(ARCH)/board/$(BOARD)/include
INC_DIR += -I$(project-dir)/arch/$(ARCH)/board/$(BOARD)/drivers/inc
INC_DIR += -I$(project-dir)/arch/$(ARCH)/board/$(BOARD)/usb
INC_DIR += -I$(project-dir)/arch/$(ARCH)/board/cpu/m3

CCFLAGS = $(ARCH_FLAGS)
CCFLAGS += $(FP_FLAGS)
CCFLAGS += $(OPTSRC)
CCFLAGS += -fmessage-length=0 -fsigned-char -ffunction-sections
CCFLAGS += -fdata-sections -ffreestanding -fno-move-loop-invariants
CCFLAGS += -Wall -Wextra -Werror -g3 
CCFLAGS += -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c
CCFLAGS += $(INC_DIR)
CCFLAGS += $(DEFINES)

ASFLAGS = $(ARCH_FLAGS)
ASFLAGS += $(FP_FLAGS)
ASFLAGS += $(OPTSRC)
ASFLAGS += -fmessage-length=0 -fsigned-char -ffunction-sections
ASFLAGS += -fdata-sections -ffreestanding -fno-move-loop-invariants
ASFLAGS += -Wall -Wextra -Werror -g3 -x assembler-with-cpp
ASFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c
ASFLAGS += $(INC_DIR)
ASFLAGS += $(DEFINES)

LDFLAGS = $(ARCH_FLAGS)
LDFLAGS += $(FP_FLAGS)
LDFLAGS += -nostdinc -nostdlib -lgcc
LDFLAGS += -Wl,--start-group -lc -lm -Wl,--end-group -Wl,-cref,-u,Reset_Handler
LDFLAGS += -Wl,-Map=$(TARGET_MAP)
LDFLAGS += -Wl,--defsym=malloc_getpagesize_P=0x80