##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

DEBUG_DIR += $(TOP_DIR)/debug/arch/arm/board/zj_v3/drivers/src

C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/misc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_adc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_bkp.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_can.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_cec.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_crc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_dac.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_dbgmcu.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_dma.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_exti.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_flash.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_fsmc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_gpio.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_i2c.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_iwdg.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_pwr.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_rcc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_rtc.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_sdio.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_spi.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_tim.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_usart.c
C_SRCS += $(TOP_DIR)/arch/arm/board/zj_v3/drivers/src/stm32f10x_wwdg.c

ASM_SRCS +=

